# Generated by Django 3.2.7 on 2021-09-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_agancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='job',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
